### ISSUE TITLE
/entryppoint.sh: line 17: Collecting: Command not found + time consuming action

### ISSUE THREAD

**Issue by guillempuigcom** [alexanderdamiani/pytester-cov#6]
Hello!!!!
I am looking for some action to apply some test coverage to a repo. I found yours and I think it has a nice approach. It is generating the expected output, nevertheless, I would like to share some observations:

* I consider the action to be **very time-consuming** (approx 6min)
See result (action stage named `pytest`)
![image](https://user-images.githubusercontent.com/62174317/126492890-12a21694-557b-4899-9256-060664eced6f.png)

> Running `pytest -rsx -p no:warnings -vv --cov=src --cov-fail-under=80 tests/` in the previous stage `Run tests & code coverage` only takes 14sec

* During the action execution, we get a `Collecting: command not found` log that should be reviewed.
**Gh action step**
```
Run alexanderdamiani/pytester-cov@v1.2.0
  with:
    pytest-root-dir: .
    cov-omit-list: tests/*
    cov-threshold-single: 10
    cov-threshold-total: 50
    requirements-file: requirements.txt
  env:
    COVERAGE_SINGLE: 60
    COVERAGE_TOTAL: 60
    pythonLocation: /opt/hostedtoolcache/Python/3.8.11/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.11/x64/lib
/usr/bin/docker run --name a33c109e5c72dc98a456d9d5cac8c44a38e33_99b42b --label 8a33c1 --workdir /github/workspace --rm -e COVERAGE_SINGLE -e COVERAGE_TOTAL -e pythonLocation -e LD_LIBRARY_PATH -e INPUT_PYTEST-ROOT-DIR -e INPUT_COV-OMIT-LIST -e INPUT_COV-THRESHOLD-SINGLE -e INPUT_COV-THRESHOLD-TOTAL -e INPUT_PYTEST-TESTS-DIR -e INPUT_REQUIREMENTS-FILE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/fluid-controller-fast-api/fluid-controller-fast-api":"/github/workspace" 8a33c1:09e5c72dc98a456d9d5cac8c44a38e33  "." "" "tests/*" "requirements.txt" "10" "50"
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/entrypoint.sh: line 17: Collecting: command not found
```
PD: I can not assign any labels to the action. I consider it as an `enhancement` :)
Warmly,
Guillem

**Comment by alexanderdamiani** [comment]
There's a few reasons for the runtime. 

1. All the dependencies must be reinstalled locally for the action, otherwise the tests will fail with `ImportError`.
2. The entire folder structure is recursed looking for any files.
3. `pytest` is ran with coverage for every file found in the recursive search.

It's then understandable the command `pytest -rsx -p no:warnings -vv --cov=src --cov-fail-under=80 tests/ in the previous stage Run tests & code coverage` is much faster.

I will look into speeding it up the action, but also feel free to open a pull request with any improvements you can make as well.

In the meantime I recommend making use of the `cov-omit-list` to reduce the runtime.

I will also take a look at the error `/entrypoint.sh: line 17: Collecting: command not found` this weekend.

**Comment by alexanderdamiani** [comment]
@guillempuigcom The two issues below have been both solved in the [latest release](https://github.com/alexanderdamiani/pytester-cov/releases/tag/v1.2.1).

`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

`/entrypoint.sh: line 17: Collecting: command not found`

I am continuing to work on improving the run-time.

**Comment by AlexHartford** [comment]
Hi, I am still experiencing:
`/entrypoint.sh: line 17: Collecting: command not found` in version 1.2.1.

Here is my config:
```yml
- name: pytest
      id: pytest
      uses: alexanderdamiani/pytester-cov@v1.2.1
      with:
        pytest-root-dir: './lambda'
        requirements-file: './lambda/requirements.txt'
```

My file structure is:
(root_dir)
  - lambda
      - lambda_function
          - lambda_function.py
          - test_lambda_function.py

Appreciate your time!

**Comment by alexanderdamiani** [comment]
You're able to locate the coverage file with my version though?

And if you can create a demo repo it'd be appreciated. I'll work out a fix this weekend.

**Comment by dmitry-engineer** [comment]
Faced the same error after the python 3.10 release. I think it would be great to choose a fixed python version. Because I made a fork and changed in Dockerfile FROM python3 to puthon3.7 and it works as before. 
Was a little confused when got an error after today off without code changing :-)

**Comment by alexanderdamiani** [comment]
@dmitry-engineer I'm hesitant to hard-code the python version to 3.7 as this could impact others running python code not backwards compatible with older versions. Also, even though there is a warning the action still functions correctly.

I am trying to make the python version an input variable for the action, however I am having trouble accessing the variable in the `Dockerfile`. I have added `python_version` as an input for the `pytester-cov` GitHub action.

Here is the current `Dockerfile`

```Dockerfile
FROM python:3
ARG python_version
RUN echo $python_version
RUN pip install pytest pytest-cov
COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
```

The issue I'm running into is the `python_version` variable is returning blank and so fails if I try to use it in the `FROM` line.

If you or anyone else has any input on how to consume GitHub action inputs in the `Dockerfile` it would be appreciated.

**Comment by alexanderdamiani** [comment]
The `/entryppoint.sh: line ...: Collecting: Command not found` error has been fixed in the latest version [v1.2.3](https://github.com/alexanderdamiani/pytester-cov/releases/tag/v1.2.3).
